#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-remote
Version  : 1.2.1
Release  : 42
URL      : https://cran.r-project.org/src/contrib/remote_1.2.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/remote_1.2.1.tar.gz
Summary  : Empirical Orthogonal Teleconnections in R
Group    : Development/Tools
License  : GPL-3.0
Requires: R-remote-lib = %{version}-%{release}
Requires: R-remote-license = %{version}-%{release}
Requires: R-Rcpp
Requires: R-gridExtra
Requires: R-latticeExtra
Requires: R-mapdata
Requires: R-raster
Requires: R-scales
BuildRequires : R-Rcpp
BuildRequires : R-gridExtra
BuildRequires : R-latticeExtra
BuildRequires : R-mapdata
BuildRequires : R-raster
BuildRequires : R-scales
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
'remote' is short for 'R(-based) EMpirical Orthogonal TEleconnections'.
    It implements a collection of functions to facilitate empirical
    orthogonal teleconnection analysis. Empirical Orthogonal Teleconnections
    (EOTs) denote a regression based approach to decompose spatio-temporal
    fields into a set of independent orthogonal patterns. They are quite
    similar to Empirical Orthogonal Functions (EOFs) with EOTs producing
    less abstract results. In contrast to EOFs, which are orthogonal in both
    space and time, EOT analysis produces patterns that are orthogonal in
    either space or time.

%package lib
Summary: lib components for the R-remote package.
Group: Libraries
Requires: R-remote-license = %{version}-%{release}

%description lib
lib components for the R-remote package.


%package license
Summary: license components for the R-remote package.
Group: Default

%description license
license components for the R-remote package.


%prep
%setup -q -n remote
pushd ..
cp -a remote buildavx2
popd
pushd ..
cp -a remote buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737155863

%install
export SOURCE_DATE_EPOCH=1737155863
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-remote
cp %{_builddir}/remote/LICENSE %{buildroot}/usr/share/package-licenses/R-remote/eb1bf76f5b21d737fc1581bc7a3bd1f22cc9fc51 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/remote/CITATION
/usr/lib64/R/library/remote/DESCRIPTION
/usr/lib64/R/library/remote/INDEX
/usr/lib64/R/library/remote/LICENSE
/usr/lib64/R/library/remote/Meta/Rd.rds
/usr/lib64/R/library/remote/Meta/data.rds
/usr/lib64/R/library/remote/Meta/features.rds
/usr/lib64/R/library/remote/Meta/hsearch.rds
/usr/lib64/R/library/remote/Meta/links.rds
/usr/lib64/R/library/remote/Meta/nsInfo.rds
/usr/lib64/R/library/remote/Meta/package.rds
/usr/lib64/R/library/remote/NAMESPACE
/usr/lib64/R/library/remote/R/remote
/usr/lib64/R/library/remote/R/remote.rdb
/usr/lib64/R/library/remote/R/remote.rdx
/usr/lib64/R/library/remote/data/australiaGPCP.RData
/usr/lib64/R/library/remote/data/datalist
/usr/lib64/R/library/remote/data/pacificSST.RData
/usr/lib64/R/library/remote/data/vdendool.RData
/usr/lib64/R/library/remote/help/AnIndex
/usr/lib64/R/library/remote/help/aliases.rds
/usr/lib64/R/library/remote/help/paths.rds
/usr/lib64/R/library/remote/help/remote.rdb
/usr/lib64/R/library/remote/help/remote.rdx
/usr/lib64/R/library/remote/html/00Index.html
/usr/lib64/R/library/remote/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/remote/libs/remote.so
/V4/usr/lib64/R/library/remote/libs/remote.so
/usr/lib64/R/library/remote/libs/remote.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-remote/eb1bf76f5b21d737fc1581bc7a3bd1f22cc9fc51
